### ISSUE TITLE
Update / simplify + cmake

### ISSUE THREAD

**Issue by DanTheColoradan** [Amanieu/asyncplusplus#8]
I really like what you have done here. Do you plan on updating it since many compilers now support C++11? There are also other enhancements that might be nice to add such as Travis-CI, cmake, and unit testing.

I forked the project and I was able to get it to compile on Mac OS X using cmake but when I ran it on Travis it bombed. I looked at the code and there was a lot I didn't understand. I can however refork if you like and merge in / show you my changes.

Mostly I'm just curious to find out what you are planning for the project if anything.

**Comment by Amanieu** [comment]
I am currently working on a few updates, including a significant rework of the scheduler (the current one has a few race conditions). I still need a bit of time to properly finish everything (maybe a week?), after which I will push my changes.

I haven't added a proper build system yet because I simply haven't had a need for it, but I think something like cmake would definitely be useful. As for testing, I have a small test program that I use locally but it is very messy.

What kind of changes did you make? I am quite interested in the error on OS X since I don't have access to a Mac and haven't been able to test my code there.

**Comment by DanTheColoradan** [comment]
Awesome! I’m excited to try it out once you are done.

And I didn’t explain the error properly. The error was on Travis / Linux using, if I remember correctly, gcc. It was probably that I was using a cmake file instead of the scripts you supply. On OS X Mavericks it compiled just fine.

The biggest reason I was thinking it would be nice to change it to cmake is that it would simplify building. Once you push your changes, I’ll give it another shot and see if I can get cmake to work. Also, I’ll give the changes you push (no cmake) a go on OS X again and let you know what my results are.

**Comment by Amanieu** [comment]
I have pushed my changes and replaced the build system with cmake.

**Comment by DanTheColoradan** [comment]
Fantastic. Closed by 15488e582a5901794325409c22bded9a79a73cc8
