### ISSUE TITLE
wrong move usage

### ISSUE THREAD

**Issue by inspirit** [Amanieu/asyncplusplus#9]
Hi,

I think that here:
https://github.com/Amanieu/asyncplusplus/blob/master/include/async%2B%2B/parallel_for.h#L43

you cant use std::move from referenced subpart object. it will generate wrong ranges for new tasks.
subpart object should be captured by value.

**Comment by Amanieu** [comment]
I don't think this is a problem, since the subpath object is only used from inside the local_task (which is guaranteed to not escape the scope of the parent function). After the local_task is spawned, the function only uses the "partitioner" object, not subpart, so it is safe to move subpart out of the parent function.

**Comment by inspirit** [comment]
ahh u right: local_task will block the function until it is done, so the function will not exit before subtask is used...
